sudo: required
services:
  - docker
language: bash
script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - travis_wait 40 docker build -t prisms/gateway-base .
  - docker run prisms/gateway-base which mosquitto
  - docker run prisms/gateway-base which influx
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      export REPO=prisms/gateway-base
      TAG=$(grep "ENV BASE_VERSION" Dockerfile | awk '{print $2}' | awk -F= '{print $2}')
      docker tag $REPO $REPO:$TAG
      docker push $REPO:$TAG
      docker push $REPO
    fi
