sudo: required
services:
  - docker
language: bash
script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t VDL-PRISM/gateway-base .
  # - docker run VDL-PRISM/gateway-base mysql --version
